create multiplication operation
develhope/Java23-Team1-Calculator pull request #2
Opened 2024-02-16 19:30 UTC by Sijia18

2024-02-19 18:18 UTC, hatefulTtamer reviewed
Revisionata

2024-02-19 18:18 UTC, hatefulTtamer commented on src/Main.java
> +        System.out.println(multiplication(0.5f, 35f));
Aggiungi altri casi per testare se il metodo funziona, prova con numeri negativi ad esempio

2024-02-19 18:18 UTC, hatefulTtamer commented on src/Main.java
> +    public static float multiplication(float n1, float n2) {
Potresti rinominare il metodo in "getMultiplication", come stavamo accordandoci nell'altra pull request (getSum)

2024-02-19 18:45 UTC, gabrielD4 commented on src/Main.java
> +    public static float multiplication(float n1, float n2) {
non avevo visto questo commento, ti ho revisionato di uniformarti a non usare get. Se già eravate d'accordo allora ritiro la review di silvio. Anche se senza get sarebbe meglio probabilmente.

2024-02-21 09:07 UTC, hatefulTtamer requested changes

2024-02-21 09:07 UTC, hatefulTtamer commented on src/Main.java
> +    public static float getMulptiplication(float n1, float n2) {
c'è un typo nel nome del metodo

2024-02-21 09:27 UTC, gabrielD4 approved these changes

2024-02-21 09:28 UTC, hatefulTtamer approved these changes

2024-02-21 09:28 UTC, merged